services:
  budgetapi:
    image: budgetapi
    build:
      context: .
      dockerfile: BudgetAPI/Dockerfile
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: budgetapi
      POSTGRES_PASSWORD: Z%4J£+5g1BEr
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"

volumes:
  pgdata: